#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    for i in range(n-1,0,-1):
        if arr[i] < arr[i-1]:
            arr[i] ,arr[i-1] = arr[i-1],arr[i]
            x = arr[:]
            x[i-1] = arr[i]
            [print(a , end = " ") for a in x]
            print()
    [print(b ,end = " ") for b in arr]

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
